"""empty message

Revision ID: 19b3932edbf7
Revises: d201021872ce
Create Date: 2018-11-18 11:17:09.355505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19b3932edbf7'
down_revision = 'd201021872ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('album_art', sa.String(length=200), nullable=True))
    op.add_column('posts', sa.Column('title', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'title')
    op.drop_column('posts', 'album_art')
    # ### end Alembic commands ###
