"""empty message

Revision ID: 52fc1ea90f86
Revises: d50a76e8995c
Create Date: 2018-08-28 21:03:06.696973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52fc1ea90f86'
down_revision = 'd50a76e8995c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('toot_visibility', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'toot_visibility')
    # ### end Alembic commands ###
