"""empty message

Revision ID: 57d4f8f6b7cd
Revises: 52fc1ea90f86
Create Date: 2018-08-30 14:08:27.599385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57d4f8f6b7cd'
down_revision = '52fc1ea90f86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('status_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'status_id')
    # ### end Alembic commands ###
