"""empty message

Revision ID: d201021872ce
Revises: 57d4f8f6b7cd
Create Date: 2018-08-30 15:33:24.661636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd201021872ce'
down_revision = '57d4f8f6b7cd'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('posts') as batch_op:
        batch_op.drop_column('post_link')

    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('posts', 'post_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('post_link', sa.VARCHAR(length=400), nullable=True))
    # ### end Alembic commands ###
